### ISSUE TITLE
Cannot npm start

### ISSUE THREAD

**Issue by numerized** [MadnessLabs/MadnessLabsPWA#1]
Hi Bro,

Thanks for amazing series on this!

I cloned your repo, I've npm install without any problem but npm start gives this in the error console:

```
Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null
    at resolve (app.core.js:2149)
    at new Promise (<anonymous>)
    at loadComponent (app.core.js:2147)
    at Object.componentOnReady (app.core.js:2143)
    at Menu.componentWillLoad (my-app.md.js:744)
    at update (app.core.js:1068)
    at plt.queue.add (app.core.js:1032)
    at doHighPriority (app.core.js:1708)

```
I don't know where to look at, can you give a little hand?

**Comment by numerized** [comment]
Houston, do you copy?
>)

**Comment by popcorn245** [comment]
Sorry for the slow reply we have been slammed here recently. I will take a look sometime tomorrow and get back with you @numerized. Have a great night! ^_^

**Comment by popcorn245** [comment]
@numerized While I was debugging your issue I updated to Ionic 4 alpha 4 and ran into an issue.  I filed a bug with Ionic team, I will keep you posted on progress.  In the meantime, try to just clone a new version of Ionic PWA toolkit as there is not much special sauce in this repo atm and you can always copy pieces you want out.   Thanks for watching and we will see you in the next video which should be out soon!  Here is the issue I filed with Ionic if you wanna keep tabs! ; ) 

https://github.com/ionic-team/stencil/issues/776

**Comment by dmunicio** [comment]
hi popcorn245, 

I am also testing your app because I also want to integrate firebase in a PWA with ionic4 and stencil 
I have also read this tutorial:
[https://itnext.io/integrating-firebase-with-a-stencil-built-pwa-865d7800b5e6](https://itnext.io/integrating-firebase-with-a-stencil-built-pwa-865d7800b5e6)

There, they say that you should do:
`import firebase from ‘firebase’`
and not
`import * as firebase from ‘firebase’`

Also, in my-app.tsx I think that "md-" is not a valid value..
```
                  <ion-icon name="md-" />
                  Apps
                </ion-item>
```
hope it helps :)

**Comment by popcorn245** [comment]
@dmunicio Thank you so much for your help!  I have been looking for a guide for how to properly import with firebase.  I implemented your feedback in the commit that closed this issue.

@numerized  Turns out the issue was because I had my ion-nav element inside of the ion-router, once I moved it out all was well again. If you pull down the latest you should be good to go after an npm install.  Thanks for contributing guys, have a great night! ^_^

**Comment by numerized** [comment]
You two rock!!

**Comment by numerized** [comment]
Just a little update.
I made it work but I had to fix versions of 

```
"@ionic/core": "4.0.0-alpha.4",
"@stencil/core": "0.8.0",
```

in package.json

I'm sure you know it but it's always better to fix version in beta phases of any tools we use for proof of concept or tutorial of this kind.

Nice work!

I'll try to push this.

**Comment by numerized** [comment]
Yeah I don't know how to do a pull request on this.
Simply do the change :))))
